services:
  frontend:
    container_name: frontend-prod
    env_file: "./frontend/.env"
    ports:
      - "3000:3000"
    restart: always
    build:
      context: "./frontend"
      dockerfile: "Dockerfile.prod"
    networks:
      - backend
#    depends_on:
#      - db
#      - api

  mobile:
    container_name: mobile-builder
    #env_file: "./mobile/.env"
    build:
      context: ./mobile
      dockerfile: "Dockerfile.prod"
    volumes:
      - "./mobile/target:/app/target"



networks:
  backend:
    driver: bridge
