services:

  server:
    env_file: "./server/.env"
    ports:
      - "8080:8080"
    build:
      context: "./server"
    volumes:
      - "./server/app:/server/app"
    restart: always
    networks:
      - area_net
    depends_on:
      - db

  # client_web:
  #   container_name: client_web
  #   env_file: "./web/.env"
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - "shared-volume:/shared"
  #   restart: always
  #   build:
  #     context: "./web"
  #   networks:
  #     - area_net
  #   depends_on:
  #     - client_mobile
  #     - server

  # client_mobile:
  #   container_name: client_mobile
  #   env_file: "./mobile/.env"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "shared-volume:/shared"
  #   restart: always
  #   build:
  #     context: "./mobile"
  #   networks:
  #     - area_net
  #   depends_on:
  #     - server

  db:
    image: postgres:17.6
    restart: always

    env_file:
      - "./server/.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - area_net

volumes:
  pgdata:
  shared-volume:

networks:
  area_net:
