services:
  client_web:
    container_name: client_web
    env_file: "./frontend/.env"
    ports:
      - "8081:3000"
    restart: always
    build:
      context: "./frontend"
      dockerfile: "Dockerfile.prod"
    volumes:
      - shared-volume:/prod/public/files
    networks:
      - area_net
    depends_on:
      - db
      - server
      - client_mobile

  client_mobile:
    container_name: client_mobile
    #env_file: "./mobile/.env"
    build:
      context: ./mobile
      dockerfile: "Dockerfile.prod"
    volumes:
      - shared-volume:/app/target

  server:
    env_file: "./server/.env"
    ports:
      - "8080:8000"
    build:
      context: "./server"
      dockerfile: "Dockerfile.prod"
    restart: always
    networks:
      - area_net
    depends_on:
      - db

  db:
    image: postgres:17.6
    container_name: pgdata
    restart: always

    env_file:
      - "./server/.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - area_net

volumes:
  pgdata:
  shared-volume: 

networks:
  area_net:

