services:
  frontend:
    container_name: area-frontend-dev
    env_file: "./frontend/.env"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - /app/node_modules
      - /app/.next
    restart: always
    build:
      context: "./frontend"
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /app
        - path: ./frontend
          action: rebuild
          ignore:
            - ./frontend/app
    networks:
      - area_net
    depends_on:
      - db
      - backend

  backend:
    container_name: area-backend-dev
    env_file: "./server/.env"
    ports:
      - "8080:8080"
    build:
      context: "./server"
    volumes:
      - "./server/app:/server/app"
      - "./server/images:/server/app/images"
    restart: always
    networks:
      - area_net
    depends_on:
      - db

  db:
    image: postgres:17.6
    container_name: pgdata
    restart: always

    env_file:
      - "./server/.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - area_net

volumes:
  pgdata:

networks:
  area_net:

